### ISSUE TITLE
Add me as credit for elasticsearch dashboard

### ISSUE THREAD

**Issue by ghost** [scalefastr/scalefastr-prometheus-grafana-dashboards#1]
Hi,

I have just recognised on your repository the ElasticSearch dashboard that looks like mine. 
For your information I posted it months ago on Grafana.net : https://grafana.com/dashboards/266

You can use and improve it, but I would be thankful if you put me as credit. More over, If you post the dashboard you should also write how to exports metrics from ElasticSearch using the Prometheus plugin for ElasticSearch : https://github.com/vvanholl/elasticsearch-prometheus-exporter

Thank you

Vincent

**Comment by InputNeuron** [comment]
I agree. My plan was to work on a way to pull down all the plugins, dashboards, build everything together and use the Grafana API and then link up everything via a build system.  

I just haven't had time yet.

This would include giving links to everyone. If you have a PR or list of URLs you'd like me to add I'll merge it or give a link back.
